var child = [
  { 'dupe': false, 'type': 64, 'name': 'address=1', 'dir': 'c0', 'linked': 5, 'url': 'http://localhost:5000/postRegister DATA:fromlogin=true&orgaccess=http&email=skipfish@example.com&city=Mountain%20View&address=1&password=skipfish&confirm_password=skipfish', 'fetched': true, 'code': 200, 'len': 269, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffbfffff },
  { 'dupe': false, 'type': 64, 'name': 'city=Mountain View', 'dir': 'c1', 'linked': 5, 'url': 'http://localhost:5000/postRegister DATA:fromlogin=true&orgaccess=http&email=skipfish@example.com&city=Mountain%20View&address=1&password=skipfish&confirm_password=skipfish', 'fetched': true, 'code': 200, 'len': 269, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffbfffff },
  { 'dupe': false, 'type': 64, 'name': 'confirm_password=skipfish', 'dir': 'c2', 'linked': 5, 'url': 'http://localhost:5000/postRegister DATA:fromlogin=true&orgaccess=http&email=skipfish@example.com&city=Mountain%20View&address=1&password=skipfish&confirm_password=skipfish', 'fetched': true, 'code': 200, 'len': 269, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffbfffff },
  { 'dupe': false, 'type': 64, 'name': 'email=skipfish@example.com', 'dir': 'c3', 'linked': 5, 'url': 'http://localhost:5000/postRegister DATA:fromlogin=true&orgaccess=http&email=skipfish@example.com&city=Mountain%20View&address=1&password=skipfish&confirm_password=skipfish', 'fetched': true, 'code': 200, 'len': 269, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffbfffff },
  { 'dupe': false, 'type': 64, 'name': 'fromlogin=true', 'dir': 'c4', 'linked': 5, 'url': 'http://localhost:5000/postRegister DATA:fromlogin=true&orgaccess=http&email=skipfish@example.com&city=Mountain%20View&address=1&password=skipfish&confirm_password=skipfish', 'fetched': true, 'code': 200, 'len': 269, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffbfffff },
  { 'dupe': false, 'type': 64, 'name': 'orgaccess=http', 'dir': 'c5', 'linked': 5, 'url': 'http://localhost:5000/postRegister DATA:fromlogin=true&orgaccess=http&email=skipfish@example.com&city=Mountain%20View&address=1&password=skipfish&confirm_password=skipfish', 'fetched': true, 'code': 200, 'len': 269, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffbfffff },
  { 'dupe': false, 'type': 64, 'name': 'password=skipfish', 'dir': 'c6', 'linked': 5, 'url': 'http://localhost:5000/postRegister DATA:fromlogin=true&orgaccess=http&email=skipfish@example.com&city=Mountain%20View&address=1&password=skipfish&confirm_password=skipfish', 'fetched': true, 'code': 200, 'len': 269, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffbfffff }
];
