var child = [
  { 'dupe': false, 'type': 4, 'name': 'Sieciowo-Superkomputerowe_files', 'dir': 'c0', 'linked': 1, 'url': 'http://localhost:5000/Sieciowo-Superkomputerowe_files/', 'fetched': true, 'code': 404, 'len': 233, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': '[none]', 'missing': true, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0x5ad29fbe },
  { 'dupe': true, 'type': 4, 'name': 'SYSTEM POCZTY STUDENCKIEJ _ Wroclawskie Centrum Sieciowo-Superkomputerowe_files', 'dir': 'c1', 'linked': 2, 'url': 'http://localhost:5000/SYSTEM%20POCZTY%20STUDENCKIEJ%20_%20Wroclawskie%20Centrum%20Sieciowo-Superkomputerowe_files/', 'fetched': true, 'code': 404, 'len': 233, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': '[none]', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x5ad29fbe },
  { 'dupe': false, 'type': 8, 'name': 'account', 'dir': 'c2', 'linked': 0, 'url': 'http://localhost:5000/account', 'fetched': true, 'code': 302, 'len': 217, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0xfff6d5cd },
  { 'dupe': true, 'type': 8, 'name': 'admin', 'dir': 'c3', 'linked': 0, 'url': 'http://localhost:5000/admin', 'fetched': true, 'code': 302, 'len': 217, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff6d5cd },
  { 'dupe': false, 'type': 8, 'name': 'form', 'dir': 'c4', 'linked': 0, 'url': 'http://localhost:5000/form', 'fetched': true, 'code': 200, 'len': 4812, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0xfff6d5cd },
  { 'dupe': true, 'type': 8, 'name': 'history', 'dir': 'c5', 'linked': 0, 'url': 'http://localhost:5000/history', 'fetched': true, 'code': 200, 'len': 4812, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff6d5cd },
  { 'dupe': false, 'type': 8, 'name': 'login', 'dir': 'c6', 'linked': 5, 'url': 'http://localhost:5000/login', 'fetched': true, 'code': 200, 'len': 4812, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 2, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0x7a2a5d4c },
  { 'dupe': true, 'type': 8, 'name': 'logout', 'dir': 'c7', 'linked': 0, 'url': 'http://localhost:5000/logout', 'fetched': true, 'code': 200, 'len': 4812, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff6d5cd },
  { 'dupe': true, 'type': 8, 'name': 'pending', 'dir': 'c8', 'linked': 0, 'url': 'http://localhost:5000/pending', 'fetched': true, 'code': 200, 'len': 4812, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff6d5cd },
  { 'dupe': false, 'type': 8, 'name': 'postRegister', 'dir': 'c9', 'linked': 5, 'url': 'http://localhost:5000/postRegister', 'fetched': true, 'code': 200, 'len': 269, 'decl_mime': 'text/html', 'sniff_mime': 'text/html', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 7, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0x1f89d6c5 },
  { 'dupe': false, 'type': 8, 'name': 'register', 'dir': 'c10', 'linked': 2, 'url': 'http://localhost:5000/register', 'fetched': true, 'code': 200, 'len': 7807, 'decl_mime': 'text/html', 'sniff_mime': 'text/html', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 2, 0, 0, 0, 0 ], 'sig': 0xfff5871a },
  { 'dupe': false, 'type': 8, 'name': 'script.js', 'dir': 'c11', 'linked': 0, 'url': 'http://localhost:5000/script.js', 'fetched': true, 'code': 200, 'len': 634, 'decl_mime': 'text/html', 'sniff_mime': 'application/javascript', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 2, 0, 0, 0, 0 ], 'sig': 0xef71a0a4 }
];
